### ISSUE TITLE
Inverse Isochron-Plotting

### ISSUE THREAD

**Issue by ANGL-40Ar39Ar** [ANGLPychron/pychron#10]
active branch=develop

active analyses=1012-13,1012-14,1012-15,1012-16,1012-17,1012-18,1012-19,1012-20,1012-21,1012-22,1012-23

description="inverse isochron pipeline, all three nodes turn green. I am able to look at the parameters in the final node but it wont plot."

Traceback
```
Traceback (most recent call last):
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\traits\trait_notifiers.py", line 394, in __call__
    self.handler(*args)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\plot\figure_container.py", line 65, in _model_changed
    self.model_changed(True)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\plot\figure_container.py", line 62, in model_changed
    self.refresh(clear=clear)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\plot\figure_container.py", line 47, in refresh
    comp.add(p.make_graph())
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\plot\panels\figure_panel.py", line 120, in make_graph
    fig.plot(plots, legend)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\plot\plotter\isochron.py", line 204, in plot
    getattr(self, '_plot_{}'.format(po.plot_name))(po, plotobj, pid)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\plot\plotter\isochron.py", line 220, in _plot_inverse_isochron
    _, _, reg = self.analysis_group.get_isochron_data(exclude_non_plateau=opt.exclude_non_plateau)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\processing\analyses\analysis_group.py", line 246, in get_isochron_data
    return calculate_isochron(ans, self.isochron_age_error_kind, reg=self.isochron_method, exclude=exclude)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\processing\argon_calculations.py", line 82, in calculate_isochron
    yint = ufloat(reg.get_intercept(), reg.get_intercept_error())
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\core\regression\new_york_regressor.py", line 151, in get_intercept_error
    e = self.get_intercept_variance() ** 0.5
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\core\regression\new_york_regressor.py", line 159, in get_intercept_variance
    self.get_slope_variance()
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\core\regression\new_york_regressor.py", line 168, in get_slope_variance
    sigbsq = 1/sum(W*U**2)
ZeroDivisionError: division by zero

```

**Comment by jirhiker** [comment]
that error would suggest you are not plotting any data. 
make sure you have Omit Non Plateau Steps and Exclude Non Plateau Steps unchecked
