### ISSUE TITLE
IC Factor for unirradiated material

### ISSUE THREAD

**Issue by ANGL-40Ar39Ar** [ANGLPychron/pychron#11]
active branch=develop

active analyses=a-01-A-497,a-01-A-498,a-01-A-499,a-01-A-500,a-01-A-501,a-01-A-502,a-01-A-503,a-01-A-504,a-01-A-505,a-01-A-506,a-01-A-507,a-01-A-508

description="Trying to run the source correction for unirradiated GA1550 biotites. I ran these in all faraday mod using the measurement script unknown600_180_Faradays"

Traceback
```
Traceback (most recent call last):
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\pyface\ui\qt4\action\action_item.py", line 371, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\pyface\tasks\action\task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\pyface\action\listening_action.py", line 74, in perform
    method()
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 348, in run
    self._run_pipeline()
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 535, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 514, in _run
    if not getattr(self.engine, func)():
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\engine.py", line 735, in run_pipeline
    node.run(state)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\nodes\fit.py", line 118, in run
    self.editor.force_update(force=True)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\plot\editors\figure_editor.py", line 85, in force_update
    model.refresh(force=force)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\plot\models\figure_model.py", line 43, in refresh
    p.make_graph()
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\plot\panels\figure_panel.py", line 120, in make_graph
    fig.plot(plots, legend)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\plot\plotter\references_series.py", line 94, in plot
    self._new_fit_series(i, p)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\plot\plotter\references_series.py", line 145, in _new_fit_series
    args = self._plot_references(pid, po)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\plot\plotter\references_series.py", line 259, in _plot_references
    data = self.reference_data(po)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\plot\plotter\references_series.py", line 180, in reference_data
    ans, xs, ys = self._get_reference_data(po)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\plot\plotter\icfactor.py", line 124, in _get_reference_data
    rys = nys / dys
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\uncertainties\core.py", line 697, in f_with_affine_output
    f_nominal_value = f(*args_values, **kwargs)
ZeroDivisionError: float division by zero

```

**Comment by jirhiker** [comment]
Is a source correction really necessary for an analysis im assuming is going to be used for sensitivity analysis.  Isn't any 36 ic factor correction going to be in the noise? especially for such an imprecise calculation (i.e sensitivity) to begin with?

However,  the error you got was because of trying to divide by zero.  That means the detector or iso:detector pair you selected for the denominator does not exist for the air analyses you are trying to fit
