### ISSUE TITLE
Sample tab

### ISSUE THREAD

**Issue by ANGL-40Ar39Ar** [ANGLPychron/pychron#22]
active branch=develop

active analyses=

description="bug when trying to access Entry-Sample

cannot open to add new samples to DB"

Traceback
```
Traceback (most recent call last):
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\pyface\ui\qt4\action\action_item.py", line 186, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\pyface\tasks\action\task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\entry\tasks\sample\actions.py", line 49, in perform
    app.get_task(pid)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\envisage\tasks\base_tasks_application.py", line 124, in get_task
    win = self.create_window(w)
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\envisage\ui\tasks\tasks_application.py", line 214, in create_window
    task = self.create_task(task_id)
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\envisage\ui\tasks\tasks_application.py", line 167, in create_task
    task = factory.create_with_extensions(extensions)
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\envisage\ui\tasks\task_factory.py", line 33, in create_with_extensions
    task = self.create(**traits)
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\envisage\ui\tasks\task_factory.py", line 28, in create
    return self.factory(**traits)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\entry\tasks\entry_plugin.py", line 183, in _sample_entry_task_factory
    from pychron.entry.tasks.sample.task import SampleEntryTask
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\entry\tasks\sample\task.py", line 29, in <module>
    from pychron.entry.tasks.sample.sample_entry import SampleEntry
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\entry\tasks\sample\sample_entry.py", line 32, in <module>
    from pychron.entry.tasks.sample.sample_edit_view import SampleEditModel, LatFloat, LonFloat, SAMPLE_ATTRS
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\entry\tasks\sample\sample_edit_view.py", line 18, in <module>
    import pyproj as pyproj
ModuleNotFoundError: No module named 'pyproj'

```

**Comment by jirhiker** [comment]
open an anaconda prompt. 

issue the following commands sequentially
```
conda activate pychron3
conda install pyproj
```
