### ISSUE TITLE
package

### ISSUE THREAD

**Issue by ANGL-40Ar39Ar** [ANGLPychron/pychron#28]
active branch=develop

active analyses=

description="adding iraddaition duration info"

Traceback
```
Traceback (most recent call last):
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\pyface\ui\qt4\action\action_item.py", line 371, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\pyface\tasks\action\task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\pyface\action\listening_action.py", line 74, in perform
    method()
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\entry\tasks\labnumber\task.py", line 399, in save_to_db
    self.manager.save()
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\entry\labnumber_entry.py", line 374, in save
    self._save_to_db(level, update, irradiation)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\entry\labnumber_entry.py", line 611, in _save_to_db
    if not self.dvc.meta_repo.smart_pull():
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\git_archive\repo_manager.py", line 846, in smart_pull
    return
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\git_archive\repo_manager.py", line 81, in __exit__
    if not self._error:
AttributeError: 'StashCTX' object has no attribute '_error'

```

**Comment by jirhiker** [comment]
Your MetaData repo is likely corrupted. archive Pychron/data/.dvc/MetaData and relaunch pychron
