### ISSUE TITLE
cannot recall or blank correct this new data

### ISSUE THREAD

**Issue by ANGL-40Ar39Ar** [ANGLPychron/pychron#30]
active branch=develop

active analyses=2358-02A

description=""

Traceback
```
Traceback (most recent call last):
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\pyface\ui\qt4\action\action_item.py", line 371, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\pyface\tasks\action\task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\pyface\action\listening_action.py", line 74, in perform
    method()
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 350, in run
    self._run_pipeline()
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 537, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 516, in _run
    if not getattr(self.engine, func)():
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\engine.py", line 730, in run_pipeline
    if not node.pre_run(state, configure=configure):
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\nodes\data.py", line 280, in pre_run
    return super(UnknownNode, self).pre_run(state, configure=True)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\nodes\base.py", line 109, in pre_run
    if self.configure(refresh=False, pre_run=True):
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\nodes\data.py", line 130, in configure
    return self.set_browser_analyses()
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\nodes\data.py", line 74, in set_browser_analyses
    is_append, analyses = self.get_browser_analyses()
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\pipeline\nodes\data.py", line 70, in get_browser_analyses
    records = self.dvc.make_analyses(records)
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\dvc\dvc.py", line 875, in make_analyses
    branches = {ei: get_repository_branch(repository_path(ei)) for ei in exps}
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\dvc\dvc.py", line 875, in <dictcomp>
    branches = {ei: get_repository_branch(repository_path(ei)) for ei in exps}
  File "C:\Users\ANGL-pychron\.pychron.0\pychron\pychron\git_archive\repo_manager.py", line 47, in get_repository_branch
    b = r.active_branch
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\git\repo\base.py", line 711, in active_branch
    return self.head.reference
  File "C:\Users\ANGL-pychron\AppData\Local\Continuum\anaconda3\envs\pychron3\lib\site-packages\git\refs\symbolic.py", line 275, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to '014c03d63d92f38227395e1f7ed255c6e098239a'

```

**Comment by jirhiker** [comment]
it appears you have a corrupted repository. not clear which one.  I suggest archiving the repository this analysis is in. e.g. using the Repository "archive" feature in pychron or goto Pychron/data/.dvc/repositories and rename the specific repo to something like `~Argus_Air231`
